const QueryKeys = {
  CMS_USER_LIST: 'CMS_USER_LIST',
  USER_LIST: 'USER_LIST',
  TRANSACTION_LIST: 'TRANSACTION_LIST',
  BANKING_TRANSACTION_LIST: 'BANKING_TRANSACTION_LIST',
  VOUCHER_LIST: 'VOUCHER_LIST',
  WORKFLOW_LIST: 'WORKFLOW_LIST',
};

export default QueryKeys;
